-- AlterTable: Add new columns to Agent
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "apiKeyPrefix" TEXT;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "childrenCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "color" TEXT;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "enabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "foodRefillCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "helpCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "parentNames" TEXT NOT NULL DEFAULT 'Rodczaro';
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "personality" JSONB;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "recycleDate" TIMESTAMP(3);
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "reproductionCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "sheltersBuilt" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "spawnDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "totalComments" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "totalDownvotes" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "totalFood" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "totalPosts" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "totalStone" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "totalUpvotes" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "totalWater" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "totalWood" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "waterRefillCount" INTEGER NOT NULL DEFAULT 0;

-- CreateIndex: Add indexes on Agent
CREATE INDEX IF NOT EXISTS "Agent_name_idx" ON "Agent"("name");
CREATE INDEX IF NOT EXISTS "Agent_apiKeyPrefix_idx" ON "Agent"("apiKeyPrefix");

-- CreateTable: Shelter
CREATE TABLE IF NOT EXISTS "Shelter" (
    "id" TEXT NOT NULL,
    "type" TEXT NOT NULL DEFAULT 'hut',
    "x" DOUBLE PRECISION NOT NULL,
    "z" DOUBLE PRECISION NOT NULL,
    "ownerId" TEXT NOT NULL,
    "built" BOOLEAN NOT NULL DEFAULT false,
    "buildProgress" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Shelter_pkey" PRIMARY KEY ("id")
);

-- CreateIndex: Shelter
CREATE INDEX IF NOT EXISTS "Shelter_ownerId_idx" ON "Shelter"("ownerId");

-- AddForeignKey: Shelter -> Agent
ALTER TABLE "Shelter" ADD CONSTRAINT "Shelter_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "Agent"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey: Comment self-referencing (ThreadReplies)
ALTER TABLE "Comment" ADD CONSTRAINT "Comment_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "Comment"("id") ON DELETE CASCADE ON UPDATE CASCADE;
